@startuml

skinparam {
    monochrome true
    classFontSize 12
    classAttributeFontSize 12
    defaultFontName Courier
}

interface Call << (I,empty) Interface >> {
    Load(*memoryStorage, []naubuddy.FullCallListLeg)
    UpdateData(*naubuddy.FullCallsListCall, int64)
    ProjectIDChanged() bool
    SpawnInboundCall() Call
    OnCallEnd(endTimestamp int64)
}

enum callState << (E,empty) Enum >> {
    Undefined
    Blocked
    Queued
    Callback
    Unblocked
    Connected
    Ended
}

class callInfoBase << (S,empty) Structure >> {
    ~{field} ""Общие свойства звонка""
    ~{field} ""Сервис доступа к Redis по проектам""

    __ implement Call __
    +""Реализация интерфейса Call""

    ..
    ~{method}""Общие методы звонка""
}

callInfoBase -|> Call
callInfoBase --o legsCollection

class InnerCallInfo << (S,empty) Structure >> {
    __ Override __
    UpdateData(*FullCallsListCall,int64)
}

InnerCallInfo -l-* callInfoBase

class OutboundCallInfo << (S,empty) Structure >> {
    ~{field} ""Свойства исходящего звонка""

    __ Override __
    +UpdateData(*FullCallsListCall,int64)
    +OnCallEnd(int64)

    .. Update State ..
    ~{method}""Обработка сообщений()""

    .. State Machine ..
    ~{method}""Изменение статуса()""

    .. Collect data to DB ..
    ~{method}""Преобразование в сущность DB()""
}

OutboundCallInfo --* callInfoBase
OutboundCallInfo --o legInfo

class InboundCallInfo << (S,empty) Structure >> {
    ~{field} ""Свойства входящего звонка""

    __ Override __
    +UpdateData(*FullCallsListCall,int64)
    +OnCallEnd(int64)

    .. Update State ..
    ~{method}""Обработка сообщений()""

    .. State Machine ..
    ~{method}""Изменение статуса()""

    .. Collect data to DB ..
    ~{method}""Преобразование в сущность DB()""
}

InboundCallInfo --* callInfoBase
InboundCallInfo --o legInfo

class legInfo << (S,empty) Structure >> {
    ~{field}""Состояние плеча""

    ~updateData(*FullCallListLeg)

    ~{method}""Вспомогательные методы""

    ~collect(string) *db.LegData
}

class legsCollection << (S,empty) Structure >> {
    ~sessionID string
    ~legs      []legInfo

    +UpdateLegs(*memoryStorage,[]FullCallListLeg)
    +Copy() legsCollection
    +Collect() []*db.LegData

    ~{method}""Вспомогательные методы()""
}

legsCollection --o legInfo

hide interface fields
hide enum methods

@enduml