@startuml

skinparam {
    monochrome true
}

start

:Получение сообщения \nFullCallList/ShortCallList;

:Сериалиация в структуру FullCallsList;

:Отправка сообщения в очередь;

fork

:Получение сообщения из очереди;

if (Состояние звонка - завершено?) then (да)
    if (Звонок есть в кэше?) then (да)
        partition "Завершение звонка" {
            :Установка времени завершения \nу каждого плеча;
            :Установка времени завершения у звонка;
            :Перевод звонка в состояние "завершен";
        }
        :Удаление звонка из кэша;
        :Преобразование в формат данных БД;
        :Сохранение в БД;
    endif
else (нет)
    partition "Создание звонка" {
        if (Звонок есть в кэше?) then (да)
            :Обновление состояние плеч;
        else (нет)
            :Создание новых плеч;
            :Обновление состояние плеч;
            'todo раскрыть как происходит определение?
            :Определение типа звонка;
            :Создание нового звонка соответствующего типа;
            :Добавление звонка в кэш;
        endif
    }
    partition "Обновление звонка" {
        :Обновление данных;
        if (Звонка нет в Redis && \nзвонок прикреплен к проекту?) then (да)
            :Сохранение звонка в Redis;
        endif
        ':Обработка события;
        'todo раскрыть
    }
    if (Прикрепленный проект изменился?) then (да)
        :Завершение звонка;
        :Создание звонка;
        :Добавление звонка в кэш;
    endif
endif

stop

@enduml



