@startuml

skinparam {
    monochrome true
}

start

:Получение сообщения FullBuddyList;

partition "Добавление задач в очередь" {
    :Добавление задачи обновления \nсписка логинов и номеров в кэше;
    :Добавление задачи обновление \nсостояния оператора;
    :Добавление задачи удаление \nотсутствующих операторв из кэша;
}

fork
:Получение задач из очреди;

:Обновление списка логинов у операторов;

partition "Обновление состояния у операторов" {
    if (Оператор онлайн?) then (да)
        :Изменение статуса оператора на "online";
    else (нет)
        :Изменение статуса оператора на "offline";
    endif
    if (Оператор ранее уже был сохранен в кэше?) then (да)
        if (Статус оператора отличается от сохраненого?) then (да)
            :Обновление статуса;
        endif
    else (нет)
        :Сохранение нового состояния у оператора;
    endif

    if (Оператор перешел в состояние wrapup?) then (да)
        :Сохранение временной метки в Redis;
    elseif (Оператор вышел из состояния wrapup?) then (да)
        :Удаление временной метки из Redis;
        :Подсчет времени нахождения в состоянии wrapup и сохранение в ns_acw;
    endif

    if (Статус оператора отличается от сохраненого?) then (да)
        :Подсчет времени нахождения в предыдущем состоянии и подсостоянии;
        :Сохранение полученных данных в ns_agent_status и ns_agent_sub_status;
    endif

    :Отправка изменений в Redis;
}

:Удаление отсутсвующих операторов;

stop


@enduml